stages:
  extraction:
    cmd: python scripts/data_extraction.py
    deps:
    - scripts/data_extraction.py 
    outs:
    - Data/raw_data.csv

  preparation:
    cmd: python scripts/data_preparation.py Data/raw_data.csv
    deps:
    - scripts/data_preparation.py
    - Data/raw_data.csv
    outs:
    - Data/preprocess_data.csv
  
  training:
    cmd: python scripts/model_training.py Data/preprocess_data.csv
    deps:
    - scripts/model_training.py
    - Data/preprocess_data.csv

  #application:
    #cmd: python scripts/application.py Data/new_data.csv
    #deps:
    #- python scripts/application.py
    #- Data/new_data.csv  