stages:
  extraction:
    cmd: python scripts/data_extraction.py
    deps:
    - scripts/data_extraction.py 
    outs:
    - Data/raw_data.csv
    - Data/new_data.csv

  preparation:
    cmd: python scripts/data_preparation.py Data/raw_data.csv Data/new_data.csv
    deps:
    - scripts/data_preparation.py
    - Data/raw_data.csv
    - Data/new_data.csv
    outs:
    - Data/preprocess_data.csv
    - Data/preprocess_new_data.csv
    - Data/preprocess_final_data.csv
  
  training:
    cmd: python scripts/model_training.py Data/preprocess_final_data.csv
    deps:
    - scripts/model_training.py
    - Data/preprocess_final_data.csv
  
  monitoring:
    cmd: python scripts/model_monitoring.py Data/preprocess_data.csv Data/preprocess_new_data.csv
    deps:
    - scripts/model_monitoring.py
    - Data/preprocess_data.csv
    - Data/preprocess_new_data.csv
    outs:
    - reports/classification_report.html
    - reports/data_drift.html
    - reports/target_drift.html
    - reports/data_quality.html

  #application:
    #cmd: python scripts/application.py Data/preprocess_new_data.csv
    #deps:
    #- python scripts/application.py
    #- Data/preprocess_new_data.csv