name: CI-CD-Pipeline
on: [push]
jobs:
  CICD-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - name: CICD
        run: |
          pip install -r requirements.txt # install python packages
          dvc pull -r origin # pull data from remote repo
          dvc repro # run the CI/CD Pipeline
                
      #- name: report
          # Create CML report
          #cat metrics.txt >> report.md
          #echo '![](./plot.png "Confusion Matrix")' >> report.md
          #cml comment create report.md
